### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by SebRut**
Signed-off-by: SebRut <sebastian.rutofski@gmail.com>

Not sure how to translate the new unit of measurement fields, should `unit_of_measurement` be translated as well or kept as is.

### CODE REVIEW

**Comment by SebRut** [comment]
in relation to #59

**Comment by pinkywafer** [comment]
I'd leave it as you have done it.  unit_of_measurement is a field used by HA so should stay as it is. 

Thanks

**Comment by pinkywafer** [comment]
The "one_time" field is also new if you can translate that also please

**Comment by pinkywafer** [comment]
Thank you

**Pull request merged**
