### PR TITLE
Rename translations dir to resolve upcoming hass incompatibility

### PR DESCRIPTION
**Pull request by tmcarr**
got an error on the latest beta of hass:

> anniversaries: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

Figured I'd offer a patch.

### CODE REVIEW

**Comment by tmcarr** [comment]
This cant be put in place until 0.109 comes out: https://github.com/home-assistant/core/pull/34494

**Comment by pinkywafer** [comment]
Thanks.  I've noticed this from my Hassfest runs.
I'm holding off on merging for a while in case any further translation file updates are received before 0.109.0 drops.  I already received one, and will be releasing on Monday.
So rebasing to latest will be required to resolve merge conflicts.
Additionally, We'll need to add the homeassistant version key to the hacs.json file to ensure it isn't installed on < 0.109.0

**Comment by pinkywafer** [comment]
if you can rebase this on the current master, and add the hacs.json key, I'll merge it, or do you want to close and I'll commit directly?

**Comment by tmcarr** [comment]
Lemme update it.

**Comment by pinkywafer** [comment]
Fantastic!  Thanks

**Pull request merged**
